
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;




import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author AFTAB COMPUTER SHOP
 */
public class AddCostumer extends javax.swing.JFrame {
    private Object lblProfPic;
    private Object boas;

    /**
     * Creates new form AddCostumer
     */
    public AddCostumer() {
        initComponents();
     autoID();
    }
    Connection conn;
    PreparedStatement pst;
    String host="";
    String user="root";
    String pass="root";
    String path = null;
    byte[] userimage = null;
    Statement s;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
   public void autoID()
 {
     
        // Class.forName("sun.jdbc.odbc.Jdb.Odbc.Driver");
        // conn=DriverManager.getConnection("jdbc:odbc:con","root","root");  
        try {
            conn =DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=project","root","root");
            s= conn.createStatement();
            // rs = s.executeQuery("select MAX(Kumar) from jatinder");
           //ResultSet rs = s.executeQuery("select MAX(child_id) from children");
             //rs.next();
            //rs.next();
           // rs.getString("MAX(Kumar)");
            //rs.getString("MAX(child_id)");
         // if (rs.getString("MAX(Kumar)") == null)
            Random rd = new Random();
            txtid.setText(""+rd.nextInt(10000+1));
         
        } catch (SQLException ex) {
            Logger.getLogger(AddCostumer.class.getName()).log(Level.SEVERE, null, ex);
        }
         // String query = "select MAX(id)  from Customers";
         
      
 }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtfirstname = new javax.swing.JTextField();
        txtlastname = new javax.swing.JTextField();
        txtcnic = new javax.swing.JTextField();
        txtpasswordid = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaddress = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtdate = new com.toedter.calendar.JDateChooser();
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        txtcontact = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtid = new javax.swing.JLabel();
        txtphoto = new javax.swing.JLabel();
        txtbrowse = new javax.swing.JButton();
        txtadd = new javax.swing.JButton();
        txtcancel = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(947, 547));
        setMinimumSize(new java.awt.Dimension(947, 547));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("First Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 190, 190, 24);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Last Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 240, 180, 24);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(247, 247, 247));
        jLabel3.setText("CNIC");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 310, 50, 20);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password ID");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 370, 110, 24);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Address");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 430, 90, 28);

        txtfirstname.setText("jTextField1");
        txtfirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfirstnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtfirstname);
        txtfirstname.setBounds(220, 190, 180, 30);
        getContentPane().add(txtlastname);
        txtlastname.setBounds(220, 240, 180, 30);

        txtcnic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcnicActionPerformed(evt);
            }
        });
        getContentPane().add(txtcnic);
        txtcnic.setBounds(220, 310, 180, 30);
        getContentPane().add(txtpasswordid);
        txtpasswordid.setBounds(220, 370, 180, 30);

        txtaddress.setColumns(20);
        txtaddress.setRows(5);
        jScrollPane1.setViewportView(txtaddress);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(220, 440, 180, 40);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date of Birth");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(420, 140, 140, 24);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Gender");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(420, 190, 110, 24);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Contact");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(420, 230, 110, 24);
        getContentPane().add(txtdate);
        txtdate.setBounds(540, 140, 160, 20);

        r1.setText("Male");
        getContentPane().add(r1);
        r1.setBounds(540, 190, 80, 23);

        r2.setText("Female");
        r2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2ActionPerformed(evt);
            }
        });
        getContentPane().add(r2);
        r2.setBounds(630, 190, 70, 23);
        getContentPane().add(txtcontact);
        txtcontact.setBounds(540, 230, 160, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Passenger ID");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(70, 140, 140, 24);

        txtid.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        txtid.setForeground(new java.awt.Color(255, 255, 255));
        txtid.setText("jLabel10");
        getContentPane().add(txtid);
        txtid.setBounds(260, 130, 150, 40);

        txtphoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtphoto);
        txtphoto.setBounds(720, 120, 200, 210);

        txtbrowse.setBackground(new java.awt.Color(0, 51, 102));
        txtbrowse.setForeground(new java.awt.Color(255, 255, 255));
        txtbrowse.setText("Browse");
        txtbrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbrowseActionPerformed(evt);
            }
        });
        getContentPane().add(txtbrowse);
        txtbrowse.setBounds(760, 340, 130, 30);

        txtadd.setBackground(new java.awt.Color(0, 51, 102));
        txtadd.setForeground(new java.awt.Color(255, 255, 255));
        txtadd.setText("Add");
        txtadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaddActionPerformed(evt);
            }
        });
        getContentPane().add(txtadd);
        txtadd.setBounds(430, 450, 150, 40);

        txtcancel.setBackground(new java.awt.Color(0, 51, 102));
        txtcancel.setForeground(new java.awt.Color(255, 255, 255));
        txtcancel.setText("Cancel");
        txtcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcancelActionPerformed(evt);
            }
        });
        getContentPane().add(txtcancel);
        txtcancel.setBounds(590, 450, 150, 40);

        jButton1.setBackground(new java.awt.Color(0, 51, 102));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(760, 450, 150, 40);

        jLabel10.setFont(new java.awt.Font("Tekton Pro", 1, 60)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 255, 255));
        jLabel10.setText("New Passenger Panel");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(220, 10, 570, 90);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\AFTAB COMPUTER SHOP\\Desktop\\Project Pic\\Adduser.jpg")); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 947, 550);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void r2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r2ActionPerformed

    private void txtfirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfirstnameActionPerformed

    private void txtcnicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcnicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcnicActionPerformed

    private void txtbrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbrowseActionPerformed
        // TODO add your handling code here:
       
        try {
             JFileChooser picchooser = new JFileChooser();
        picchooser.showOpenDialog(null);
        File pic = picchooser.getSelectedFile();
        
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.images","png","jpg");
        picchooser.addChoosableFileFilter(filter);
        
        path = pic.getAbsolutePath();
        BufferedImage img;
            
            img = ImageIO.read(picchooser.getSelectedFile());
             ImageIcon imageIcon = new ImageIcon(new 
        ImageIcon(img).getImage().getScaledInstance(250,250,Image.SCALE_DEFAULT));
        txtphoto.setIcon(imageIcon);
       
        File image = new File(path);
        FileInputStream fis = new  FileInputStream(image);
        ByteArrayOutputStream baos = new  ByteArrayOutputStream();
        byte[] buff = new byte[1024];
        for(int readNum; (readNum=fis.read(buff)) !=-1 ; )
        {
            baos.write(buff,0,readNum);
        }
        userimage=baos.toByteArray();
        } catch (IOException ex) {
            Logger.getLogger(AddCostumer.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_txtbrowseActionPerformed

    private void txtaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaddActionPerformed
        // TODO add your handling code here:
        
        String firstname = txtfirstname.getText();
        String lastname = txtlastname.getText();
        String cnic = txtcnic.getText();
        String password = txtpasswordid.getText();
        String address = txtaddress.getText();
        DateFormat da = new SimpleDateFormat("yyyy-MM-dd");
        String date = da.format(txtdate.getDate());
        String Gender;
        
        if(r1.isSelected())
        {
            Gender = "Male";
        }
        else
        {
            Gender = "Female";
        }
        String contact = txtcontact.getText();
        try {
            conn =DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=project","root","root");
            pst = conn.prepareStatement("insert into AddCustomer(Cus_ID,firstname,lastname,NIC,passwordID,Adress,DOB,gender,contact,picture)values(?,?,?,?,?,?,?,?,?,?)");
            pst.setString(1,txtid.getText());
            pst.setString(2,firstname);
            pst.setString(3,lastname);
            pst.setString(4,cnic );
            pst.setString(5,password);
            pst.setString(6,address );
            pst.setString(7,date);
            pst.setString(8,Gender);
            pst.setString(9,contact);
            pst.setBytes(10, userimage);
            pst.execute();
            JOptionPane.showMessageDialog(null,"Registration Created.....");
           
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(AddCostumer.class.getName()).log(Level.SEVERE, null, ex);
        }
        
                
        
    }//GEN-LAST:event_txtaddActionPerformed

    private void txtcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcancelActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_txtcancelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        MainPage obj = new MainPage();
        obj.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCostumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCostumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCostumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCostumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCostumer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JButton txtadd;
    private javax.swing.JTextArea txtaddress;
    private javax.swing.JButton txtbrowse;
    private javax.swing.JButton txtcancel;
    private javax.swing.JTextField txtcnic;
    private javax.swing.JTextField txtcontact;
    private com.toedter.calendar.JDateChooser txtdate;
    private javax.swing.JTextField txtfirstname;
    private javax.swing.JLabel txtid;
    private javax.swing.JTextField txtlastname;
    private javax.swing.JTextField txtpasswordid;
    private javax.swing.JLabel txtphoto;
    // End of variables declaration//GEN-END:variables
}
