
import java.awt.Image;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Random;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author AFTAB COMPUTER SHOP
 */
public class Ticket extends javax.swing.JFrame {

    /**
     * Creates new form Ticket
     */
    public Ticket() {
        initComponents();
        autoID();
    }
    public void autoID()
    {
          Random rd = new Random();
            txtid.setText(""+rd.nextInt(10000+1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtsource = new javax.swing.JComboBox();
        txtdept = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtid = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtcusid = new javax.swing.JTextField();
        txtfirstname = new javax.swing.JLabel();
        txtlastname = new javax.swing.JLabel();
        txtpassword = new javax.swing.JLabel();
        txtflightno = new javax.swing.JLabel();
        txtflightname = new javax.swing.JLabel();
        txtdeparttime = new javax.swing.JLabel();
        txtclass = new javax.swing.JComboBox();
        txtprice = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txttotal = new javax.swing.JLabel();
        txtseat = new javax.swing.JSpinner();
        txtdate = new com.toedter.calendar.JDateChooser();
        jButton5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(947, 547));
        setMinimumSize(new java.awt.Dimension(947, 547));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Sealect Country");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 170, 270, 42);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Source");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 250, 80, 24);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Destination");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(220, 250, 110, 24);

        txtsource.setForeground(new java.awt.Color(0, 51, 51));
        txtsource.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "America", "Australia", "Germany", "Canada", "Pakistan", "India", "Londan" }));
        getContentPane().add(txtsource);
        txtsource.setBounds(20, 290, 130, 30);

        txtdept.setForeground(new java.awt.Color(0, 51, 51));
        txtdept.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "America", "Australia", "Germany", "Canada", "Pakistan", "India", "Londan" }));
        txtdept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdeptActionPerformed(evt);
            }
        });
        getContentPane().add(txtdept);
        txtdept.setBounds(190, 290, 140, 30);

        jTable1.setBackground(new java.awt.Color(0, 51, 51));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight ID", "Flight Name", "Source", "Departure", "Date", "DeptTime", "ArrTimel", "Charge"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 360, 480, 170);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ticket No");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(470, 150, 170, 42);

        txtid.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtid.setForeground(new java.awt.Color(255, 255, 255));
        txtid.setText("Ticket No");
        getContentPane().add(txtid);
        txtid.setBounds(490, 190, 90, 22);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("First Name");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(630, 100, 93, 24);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Last Name");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(630, 140, 92, 24);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Customer ID");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(630, 50, 120, 24);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Password no");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(630, 180, 105, 24);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Flight no");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(630, 220, 73, 24);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Flight Name");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(630, 260, 102, 24);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Depart Time");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(630, 300, 107, 24);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Class");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(630, 340, 45, 24);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Price");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(630, 420, 44, 24);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Seat");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(630, 380, 38, 24);

        txtcusid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcusidActionPerformed(evt);
            }
        });
        getContentPane().add(txtcusid);
        txtcusid.setBounds(750, 50, 150, 30);

        txtfirstname.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtfirstname.setForeground(new java.awt.Color(255, 255, 255));
        txtfirstname.setText("jLabel16");
        getContentPane().add(txtfirstname);
        txtfirstname.setBounds(760, 100, 68, 22);

        txtlastname.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtlastname.setForeground(new java.awt.Color(255, 255, 255));
        txtlastname.setText("jLabel17");
        getContentPane().add(txtlastname);
        txtlastname.setBounds(760, 140, 68, 22);

        txtpassword.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtpassword.setForeground(new java.awt.Color(255, 255, 255));
        txtpassword.setText("jLabel18");
        getContentPane().add(txtpassword);
        txtpassword.setBounds(760, 180, 130, 22);

        txtflightno.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtflightno.setForeground(new java.awt.Color(255, 255, 255));
        txtflightno.setText("jLabel19");
        getContentPane().add(txtflightno);
        txtflightno.setBounds(760, 220, 100, 22);

        txtflightname.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtflightname.setForeground(new java.awt.Color(255, 255, 255));
        txtflightname.setText("jLabel20");
        getContentPane().add(txtflightname);
        txtflightname.setBounds(760, 260, 120, 22);

        txtdeparttime.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtdeparttime.setForeground(new java.awt.Color(255, 255, 255));
        txtdeparttime.setText("jLabel21");
        getContentPane().add(txtdeparttime);
        txtdeparttime.setBounds(760, 300, 120, 22);

        txtclass.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Economy", "First", "Business" }));
        getContentPane().add(txtclass);
        txtclass.setBounds(730, 340, 150, 30);

        txtprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpriceActionPerformed(evt);
            }
        });
        getContentPane().add(txtprice);
        txtprice.setBounds(730, 420, 150, 30);

        jButton1.setBackground(new java.awt.Color(0, 102, 153));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(610, 500, 110, 30);

        jButton2.setBackground(new java.awt.Color(0, 102, 153));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(730, 500, 100, 30);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(350, 320, 110, 30);

        jButton4.setBackground(new java.awt.Color(204, 204, 255));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jButton4.setForeground(new java.awt.Color(51, 51, 255));
        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(840, 90, 100, 30);

        txttotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txttotal.setForeground(new java.awt.Color(255, 0, 51));
        txttotal.setText("RS");
        getContentPane().add(txttotal);
        txttotal.setBounds(500, 510, 110, 30);

        txtseat.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txtseatStateChanged(evt);
            }
        });
        getContentPane().add(txtseat);
        txtseat.setBounds(730, 380, 150, 30);
        getContentPane().add(txtdate);
        txtdate.setBounds(730, 460, 150, 30);

        jButton5.setBackground(new java.awt.Color(0, 102, 153));
        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(840, 500, 100, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Date");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(630, 460, 41, 24);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Total Price:");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(510, 470, 110, 24);

        jLabel19.setFont(new java.awt.Font("Tekton Pro", 1, 65)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 102, 255));
        jLabel19.setText("Ticket Generater ");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(10, 10, 480, 80);

        jLabel20.setFont(new java.awt.Font("Tekton Pro", 1, 65)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 102, 255));
        jLabel20.setText("Panel");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(170, 80, 180, 60);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\AFTAB COMPUTER SHOP\\Desktop\\Project Pic\\ticket.jpg")); // NOI18N
        getContentPane().add(jLabel18);
        jLabel18.setBounds(0, 0, 950, 550);

        jLabel21.setText("jLabel21");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(200, 100, 40, 14);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
        String source = txtsource.getSelectedItem().toString();
        String dept= txtdept.getSelectedItem().toString();
        try {
            Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=project","root","root");
            PreparedStatement pst = conn.prepareStatement("select * from Flight where Source=? and Department = ?");
            pst.setString(1, source);
             pst.setString(2, dept);
             ResultSet rs = pst.executeQuery();
             
             ResultSetMetaData rsm=rs.getMetaData();
             int c;
             c = rsm.getColumnCount();
             DefaultTableModel df = ( DefaultTableModel)jTable1.getModel();
             df.setRowCount(0);
             while(rs.next())
             {
                 Vector v2 = new Vector();
                 for (int i = 1; i < c; i++) {
                     v2.add(rs.getString("Flight_ID"));
                     v2.add(rs.getString("Flight_Name"));
                     v2.add(rs.getString("Source"));
                     v2.add(rs.getString("Department"));
                     v2.add(rs.getString("Dated"));
                     v2.add(rs.getString("Depature_time"));
                     v2.add(rs.getString("Arrival_Time"));
                     v2.add(rs.getString("Flight_Charge"));
                     
                 }
                 df.addRow(v2);
             }
        } catch (SQLException ex) {
            Logger.getLogger(Ticket.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtdeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdeptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdeptActionPerformed

    private void txtcusidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcusidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcusidActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         String id = txtcusid.getText();
         Connection conn;
        try {
            conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=project","root","root");
             PreparedStatement pst = conn.prepareStatement("select * from Addcustomer where Cus_ID=?");
         pst.setString(1, id);
         ResultSet rs = pst.executeQuery();
         if(rs.next()==false)
         {
             JOptionPane.showMessageDialog(this, "Record not Found");
         }
         else
         {
             String fname = rs.getString("firstname");
             String Lname = rs.getString("lastname");
             String password = rs.getString("passwordID");
             
             
             
             txtfirstname.setText(fname.trim());
             txtlastname.setText(Lname.trim()); 
             txtpassword.setText(password.trim());
             
             
         }
        
        } catch (SQLException ex) {
            Logger.getLogger(Ticket.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:////////////
          DefaultTableModel df = ( DefaultTableModel)jTable1.getModel();
          int selectIndex = jTable1.getSelectedRow();
          txtflightno.setText(df.getValueAt(selectIndex,0).toString());
          txtflightname.setText(df.getValueAt(selectIndex,1).toString());
          txtdeparttime.setText(df.getValueAt(selectIndex,5).toString());
          txtprice.setText(df.getValueAt(selectIndex,7).toString());
                      
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpriceActionPerformed

    private void txtseatStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txtseatStateChanged
        // TODO add your handling code here:
        int price = Integer.parseInt(txtprice.getText());
        int seat = Integer.parseInt(txtseat.getValue().toString());
        int total = price*seat;
        txttotal.setText(String.valueOf(total));
    }//GEN-LAST:event_txtseatStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          // TODO add your handling code here:
        String ticketID = txtid.getText();
        String flightID = txtflightno.getText();
        String CusID = txtcusid.getText();
        String classess = txtclass.getSelectedItem().toString().trim();
        String price = txtprice.getText();
        String seat = txtseat.getValue().toString();
        
        DateFormat da = new SimpleDateFormat("yyyy-MM-dd");
        String date = da.format(txtdate.getDate());
        
        try {
            Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=project","root","root");
            PreparedStatement pst = conn.prepareStatement("insert into ticket(id,flight_ID,Cus_ID,Class,Price,seats,date)values(?,?,?,?,?,?,?)");
            pst.setString(1,ticketID);
            pst.setString(2,flightID);
            pst.setString(3,CusID);
            pst.setString(4,classess);
            pst.setString(5,price);
            pst.setString(6,seat );
            pst.setString(7,date);

            pst.execute();
            JOptionPane.showMessageDialog(null,"Ticket is Booked.....");
           
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(AddCostumer.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        MainPage obj = new MainPage();
        obj.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ticket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox txtclass;
    private javax.swing.JTextField txtcusid;
    private com.toedter.calendar.JDateChooser txtdate;
    private javax.swing.JLabel txtdeparttime;
    private javax.swing.JComboBox txtdept;
    private javax.swing.JLabel txtfirstname;
    private javax.swing.JLabel txtflightname;
    private javax.swing.JLabel txtflightno;
    private javax.swing.JLabel txtid;
    private javax.swing.JLabel txtlastname;
    private javax.swing.JLabel txtpassword;
    private javax.swing.JTextField txtprice;
    private javax.swing.JSpinner txtseat;
    private javax.swing.JComboBox txtsource;
    private javax.swing.JLabel txttotal;
    // End of variables declaration//GEN-END:variables
}
